2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110940-2kvpsvny/logs/debug.log
2021-09-21 11:09:40,958 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_110940-2kvpsvny/logs/debug-internal.log
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:_jupyter_setup():300] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f56b5c8b3d0>
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:09:40,959 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 1var4zkz
2021-09-21 11:09:40,961 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/gta/1var4zkz
2021-09-21 11:09:40,962 INFO    MainThread:21744 [wandb_run.py:_atexit_cleanup():1575] got exitcode: 0
2021-09-21 11:09:40,962 INFO    MainThread:21744 [wandb_run.py:_restore():1547] restore
2021-09-21 11:09:41,010 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:09:41,471 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 973
}

2021-09-21 11:09:41,959 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 2
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 1300
}

2021-09-21 11:09:42,063 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4822
}

2021-09-21 11:09:42,166 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4822
}

2021-09-21 11:09:42,268 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4822
}

2021-09-21 11:09:42,370 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4822
}

2021-09-21 11:09:42,472 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 973
  total_bytes: 4822
}

2021-09-21 11:09:42,575 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:42,677 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:42,781 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:42,884 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:42,986 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:43,089 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:43,375 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}

2021-09-21 11:09:44,304 INFO    MainThread:21744 [wandb_run.py:_wait_for_finish():1697] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 4822
  total_bytes: 4822
}
local_info {
}

2021-09-21 11:09:45,578 INFO    MainThread:21744 [wandb_run.py:_show_files():1947] logging synced files
2021-09-21 11:09:45,587 INFO    MainThread:21744 [wandb_init.py:init():430] starting backend
2021-09-21 11:09:45,587 INFO    MainThread:21744 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2021-09-21 11:09:45,590 INFO    MainThread:21744 [backend.py:ensure_launched():135] starting backend process...
2021-09-21 11:09:45,595 INFO    MainThread:21744 [backend.py:ensure_launched():139] started backend process with pid: 23451
2021-09-21 11:09:45,596 INFO    MainThread:21744 [wandb_init.py:init():435] backend started and connected
2021-09-21 11:09:45,613 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():819] probe notebook
2021-09-21 11:09:45,614 INFO    MainThread:21744 [wandb_run.py:_label_probe_notebook():826] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-09-21 11:09:45,614 INFO    MainThread:21744 [wandb_init.py:init():494] updated telemetry
2021-09-21 11:09:45,614 INFO    MainThread:21744 [wandb_init.py:init():517] communicating current version
2021-09-21 11:09:46,575 INFO    MainThread:21744 [wandb_init.py:init():522] got version response 
2021-09-21 11:09:46,575 INFO    MainThread:21744 [wandb_init.py:init():530] communicating run to backend with 30 second timeout
2021-09-21 11:09:47,058 INFO    MainThread:21744 [wandb_init.py:init():557] starting run threads in backend
2021-09-21 11:09:48,105 INFO    MainThread:21744 [wandb_run.py:_console_start():1605] atexit reg
2021-09-21 11:09:48,106 INFO    MainThread:21744 [wandb_run.py:_redirect():1479] redirect: SettingsConsole.WRAP
2021-09-21 11:09:48,106 INFO    MainThread:21744 [wandb_run.py:_redirect():1516] Wrapping output streams.
2021-09-21 11:09:48,108 INFO    MainThread:21744 [wandb_run.py:_redirect():1540] Redirects installed.
2021-09-21 11:09:48,108 INFO    MainThread:21744 [wandb_init.py:init():582] run started, returning control to user process
2021-09-21 11:09:48,197 INFO    MainThread:21744 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-21 11:09:48,197 INFO    MainThread:21744 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 11:10:33,210 INFO    MainThread:21744 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-21 11:10:33,212 INFO    MainThread:21744 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-21 11:10:33,212 INFO    MainThread:21744 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 11:10:36,522 INFO    MainThread:21744 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-21 11:10:36,523 INFO    MainThread:21744 [wandb_init.py:_pause_backend():262] pausing backend
2021-09-21 11:10:36,524 INFO    MainThread:21744 [jupyter.py:save_ipynb():298] not saving jupyter notebook
2021-09-21 11:11:36,840 INFO    MainThread:21744 [wandb_init.py:_resume_backend():271] resuming backend
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting env: {}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_setup.py:_flush():69] setting login settings: {'api_key': 'ad99ac37ad8156aa2d4e230770e7dbe838e860b0'}
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:_log_setup():348] Logging user logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111136-1n8uc4gl/logs/debug.log
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:_log_setup():349] Logging internal logs to /root/Source/Set-Tree/graphtree/wandb/run-20210921_111136-1n8uc4gl/logs/debug-internal.log
2021-09-21 11:11:36,848 INFO    MainThread:21744 [wandb_init.py:init():381] calling init triggers
2021-09-21 11:11:36,849 INFO    MainThread:21744 [wandb_init.py:init():386] wandb.init called with sweep_config: {}
config: {}
2021-09-21 11:11:36,849 INFO    MainThread:21744 [wandb_init.py:init():401] re-initializing run, found existing run on stack: 2kvpsvny
2021-09-21 11:11:36,850 INFO    MainThread:21744 [wandb_run.py:finish():1275] finishing run mlwell-rgb/Set-Tree-graphtree/2kvpsvny
